name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - matplotlib
  - pandas
  -scipy
conda activate example-environment
conda env export --from-history -f environment.yml  
  
 
